version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379 
    networks:
      - red-docker

  app:
    image: modak-ratelimit
    ports:
      - "8080:8080"  
    networks:
      - red-docker

networks:
  red-docker:
